### ISSUE TITLE
Support Function in options

### ISSUE THREAD

**Issue by ronanquillevere** [highcharts4gwt/highcharts4gwt#4]

**Comment by duns** [comment]
This one would be nice to have...

**Comment by ronanquillevere** [comment]
Yes I know, I will work on that soon.

Maybe, first as a workaround I will add something like the following 
```Java
setFieldAsJsonObject(fieldName, fieldValueAsJsonObject)
```

but specificaly for Functions (replacing the Json.parse by an eval). So that it is possible to set a function for formatter etc.

Then I will have a look at how to pass a java function (probably will look like the event handling)

**Comment by ronanquillevere** [comment]
I commited the basic support for functions. For more advanced support I will need highcharts team to make some changes. Not sure they will do it, we will see :)

**Comment by ronanquillevere** [comment]
#4b3fda8f9524a8cd1e7706bbb625418ff241799c
